### PR TITLE
Enabled registrations endpoint to accept json

### PR DESCRIPTION
**Pull request by agnessa**
https://www.pivotaltracker.com/story/show/159031907

### CODE REVIEW

**Comment by agnessa** [comment]
I believe this is not the complete work on the registration endpoint, because of pending clarifications here: https://basecamp.com/1756858/projects/13795275/messages/79511128

However, maybe good to merge already as it allows to develop a minimum registration (email, first name, last name).

**Review by Bluesmile82 — APPROVED** [review]
Works fine! The backend sign up form is not working as it doesn't have first or last name fields. But we won't use it anyway.

**Comment by agnessa** [comment]
I fixed the html signup form to keep it consistent

**Review by santostiago — APPROVED** [review]
LGTM!

**Pull request merged**
