### PR TITLE
Sections endpoints

### PR DESCRIPTION
**Pull request by agnessa**
This adds the /sections and /sections/:slug endpoint. Both can be parametrised using `includes` parameter to return nested information as follows:

`/api/v1/sections`

```
[
   {
      "title":"Planning",
      "slug":"planning"
   },
   {
      "title":"Tracking",
      "slug":"tracking"
   }
]
```

`/api/v1/sections?includes[]=categories`

```
[
   {
      "title":"Planning",
      "slug":"planning",
      "categories":[
         {
            "title":"NDC Targets",
            "slug":"ndc_targets"
         },
         ...
      ]
   },
  ...
]
```

`/api/v1/sections?includes[]=categories&includes[]=targets`

```
[
   {
      "title":"Planning",
      "slug":"planning",
      "categories":[
         {
            "title":"NDC Targets",
            "slug":"ndc_targets",
            "targets":[
               {
                  "title":"GHG Target",
                  "slug":"ghg_target"
               },
               {
                  "title":"Non-GHG Target",
                  "slug":"ghg_target"
               }
            ]
         },
         ...
      ]
   },
  ...
]
```

### CODE REVIEW

**Review by Bluesmile82 — APPROVED** [review]
Looks and works nicely! It would be nice to add some API documentation

**Review by simaob — APPROVED** [review]
Looks good to me. =)

**Comment by agnessa** [comment]
Happy to add documentation, what do you normally use?

**Comment by simaob** [comment]
Previously on CW and ESP we added a markdown file with it. But maybe something a little smart but not too far from the tree would be good. (Maybe even on Gitbooks?)

**Pull request merged**
